/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "!./src/pages/LoginPage.jsx",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bec6e0",
        "on-primary-container": "#7c839b",
        "primary-fixed": "#dae2fd",
        "on-surface": "#191c1e",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#3f465c",
        "secondary": "#0058be",
        "surface": "#f7f9fb",
        "tertiary-container": "#0b1c30",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed": "#001a42",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#b7c8e1",
        "tertiary-fixed": "#d3e4fe",
        "on-primary-fixed": "#131b2e",
        "outline": "#76777d",
        "on-secondary-fixed-variant": "#004395",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#45464d",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "secondary-fixed": "#d8e2ff",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-tint": "#565e74",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-container-highest": "#e0e3e5",
        "tertiary": "#000000",
        "on-secondary-container": "#fefcff",
        "surface-container": "#eceef0",
        "primary-container": "#131b2e",
        "secondary-container": "#2170e4",
        "on-tertiary-fixed": "#0b1c30",
        "outline-variant": "#c6c6cd",
        "primary": "#000000",
        "on-tertiary-container": "#75859d",
        "inverse-primary": "#bec6e0",
        "on-error": "#ffffff",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        base: "8px",
        lg: "24px",
        md: "16px",
        sm: "12px",
        xl: "32px",
        gutter: "20px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        xs: "4px"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "900" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
